apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q98wyacsc-go 
  janus-idp.io/tekton: q98wyacsc-go
  backstage.io/kubernetes-id: q98wyacsc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q98wyacsc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml